// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationETS.Data;

#nullable disable

namespace WebApplicationETS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250922053326_CreateOfficeTable")]
    partial class CreateOfficeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.Office.Office", b =>
                {
                    b.Property<int>("officeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("officeId"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cityZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("disableTransportCutoffDays")
                        .HasColumnType("int");

                    b.Property<bool>("disableTransportJob")
                        .HasColumnType("bit");

                    b.Property<string>("dispName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("driverAppIVRNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("helpDeskContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAutoPenalty")
                        .HasColumnType("bit");

                    b.Property<bool>("isPanicSound")
                        .HasColumnType("bit");

                    b.Property<decimal>("lat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("lng")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("locCode")
                        .HasColumnType("int");

                    b.Property<short>("locGroup")
                        .HasColumnType("smallint");

                    b.Property<string>("locName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("modBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("modOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("shortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sosContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userAppIVRNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("officeId");

                    b.ToTable("Office");
                });

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.VehicleCompliances.LkpBillPlanType", b =>
                {
                    b.Property<string>("bptCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<string>("bptName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("modOn")
                        .HasColumnType("datetime2");

                    b.HasKey("bptCode");

                    b.ToTable("LkpBillPlanTypes");
                });

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.VehicleCompliances.LkpCurrentStatus", b =>
                {
                    b.Property<int>("currentStatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("currentStatusCode"));

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<string>("currentStatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("currentStatusCode");

                    b.ToTable("LkpCurrentStatuses");
                });

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.VehicleCompliances.LkpFuelType", b =>
                {
                    b.Property<int>("fuelTypeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fuelTypeCode"));

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<string>("fuelTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fuelTypeCode");

                    b.ToTable("LkpFuelTypes");
                });

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.VehicleCompliances.LkpGpsProvider", b =>
                {
                    b.Property<int>("gpsProviderCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gpsProviderCode"));

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<string>("gpsProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("gpsProviderCode");

                    b.ToTable("LkpGpsProviders");
                });

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.VehicleCompliances.LkpVehicleModel", b =>
                {
                    b.Property<int>("modelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("modelId"));

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("locCode")
                        .HasColumnType("int");

                    b.Property<string>("modelDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("vehicleTypeCode")
                        .HasColumnType("int");

                    b.HasKey("modelId");

                    b.ToTable("LkpVehicleModels");
                });

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.VehicleCompliances.LkpVehicleStatus", b =>
                {
                    b.Property<int>("vehicleStatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vehicleStatusCode"));

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<string>("vehicleStatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vehicleStatusCode");

                    b.ToTable("LkpVehicleStatuses");
                });

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.VehicleCompliances.LkpVehicleType", b =>
                {
                    b.Property<int>("vehicleTypeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vehicleTypeCode"));

                    b.Property<short>("capacity")
                        .HasColumnType("smallint");

                    b.Property<int>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("locCode")
                        .HasColumnType("int");

                    b.Property<int>("modBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("modOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("vehicleTypeDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vehicleTypeCode");

                    b.ToTable("LkpVehicleTypes");
                });

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.VehicleCompliances.Vehicle", b =>
                {
                    b.Property<int>("vehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vehicleId"));

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bpId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ccpermitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("chassisNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("cngEndorsementInRc")
                        .HasColumnType("bit");

                    b.Property<int>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("currentStatus")
                        .HasColumnType("int");

                    b.Property<int>("driverId")
                        .HasColumnType("int");

                    b.Property<string>("engineCapacityCc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fireExtinguisherDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("firstAidKidDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fitnessExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("fuelTypeCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("gpsInstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("gpsProviderCode")
                        .HasColumnType("int");

                    b.Property<string>("insuranceAgencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("insuranceExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("isGpsInstalled")
                        .HasColumnType("bit");

                    b.Property<int?>("kmsRunBeforeOnboarding")
                        .HasColumnType("int");

                    b.Property<int>("locCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("makeYear")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("mandatorySignage")
                        .HasColumnType("bit");

                    b.Property<int?>("modBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("modOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("model")
                        .HasColumnType("int");

                    b.Property<string>("ownerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ownerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ownerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("passengerTaxDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("permitExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("pucExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("registrationExpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("roadTaxValidityExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("trackeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trackeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("transporterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("validTokenTaxDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("vehicleInductionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("vehicleRegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("vehicleRegistrationNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("vehicleStatus")
                        .HasColumnType("int");

                    b.Property<int>("vehicleTypeCode")
                        .HasColumnType("int");

                    b.HasKey("vehicleId");

                    b.HasIndex("vehicleRegistrationNo")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.VendorCompliances.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorId"));

                    b.Property<bool?>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BPID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ContactFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContactTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAILID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LOCCODE")
                        .HasColumnType("int");

                    b.Property<string>("MOBILE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MODBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODON")
                        .HasColumnType("datetime2");

                    b.Property<string>("PREFIXTAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REMARKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SINGLEPLAN")
                        .HasColumnType("bit");

                    b.Property<int?>("TRANSPORTERID")
                        .HasColumnType("int");

                    b.Property<string>("VENDOR_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");
                });
#pragma warning restore 612, 618
        }
    }
}
