// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationETS.Data;

#nullable disable

namespace WebApplicationETS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250829043234_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.VehicleCompliances.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int>("Bpid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CcpermitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChassisNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("CngEndorsementInRc")
                        .HasColumnType("bit");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("EngineCapacityCc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FireExtinguisherDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstAidKidDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FitnessExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuelTypeCode")
                        .HasColumnType("int");

                    b.Property<int?>("GPSProviderCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GpsInstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsuranceAgencyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("InsuranceExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsGpsInstalled")
                        .HasColumnType("bit");

                    b.Property<int?>("KmsRunBeforeOnboarding")
                        .HasColumnType("int");

                    b.Property<int>("LocCode")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("MakeYear")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("MandatorySignage")
                        .HasColumnType("bit");

                    b.Property<int?>("ModBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OwnerAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PassengerTaxDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PermitExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PucExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RegistrationExpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RoadTaxValidityExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrackeeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrackeeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TransporterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidTokenTaxDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VehicleInductionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VehicleRegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleRegistrationNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VehicleStatus")
                        .HasColumnType("int");

                    b.Property<int>("VehicleTypeCode")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("VehicleRegistrationNo")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.VehicleCompliances.lkpBillPlanType", b =>
                {
                    b.Property<string>("BPTCODE")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("BPTNAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("createdby")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.HasKey("BPTCODE");

                    b.ToTable("lkpBillPlanTypes");
                });

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.VendorCompliances.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorId"));

                    b.Property<bool?>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BPID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ContactFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContactTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAILID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LOCCODE")
                        .HasColumnType("int");

                    b.Property<string>("MOBILE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MODBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODON")
                        .HasColumnType("datetime2");

                    b.Property<string>("PREFIXTAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REMARKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SINGLEPLAN")
                        .HasColumnType("bit");

                    b.Property<int?>("TRANSPORTERID")
                        .HasColumnType("int");

                    b.Property<string>("VENDOR_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");
                });
#pragma warning restore 612, 618
        }
    }
}
