// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationETS.Data;

#nullable disable

namespace WebApplicationETS.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.VehicleCompliances.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int?>("Bpid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CcpermitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChassisNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CngEndorsementInRc")
                        .HasColumnType("bit");

                    b.Property<int?>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("EngineCapacityCc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FireExtinguisherDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstAidKidDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FitnessExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FuelTypeCode")
                        .HasColumnType("int");

                    b.Property<int?>("GPSProviderCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GpsInstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsuranceAgencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsuranceExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsGpsInstalled")
                        .HasColumnType("bit");

                    b.Property<int?>("KmsRunBeforeOnboarding")
                        .HasColumnType("int");

                    b.Property<int?>("LocCode")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MakeYear")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("MandatorySignage")
                        .HasColumnType("bit");

                    b.Property<int?>("ModBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PassengerTaxDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PermitExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PucExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegistrationExpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RoadTaxValidityExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrackeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransporterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidTokenTaxDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VehicleInductionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VehicleRegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleRegistrationNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleStatus")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleTypeCode")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("WebApplicationETS.Model.Compliances.VendorCompliances.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorId"));

                    b.Property<bool?>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BPID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ContactFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContactTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAILID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LOCCODE")
                        .HasColumnType("int");

                    b.Property<string>("MOBILE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MODBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODON")
                        .HasColumnType("datetime2");

                    b.Property<string>("PREFIXTAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REMARKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SINGLEPLAN")
                        .HasColumnType("bit");

                    b.Property<int?>("TRANSPORTERID")
                        .HasColumnType("int");

                    b.Property<string>("VENDOR_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");
                });
#pragma warning restore 612, 618
        }
    }
}
